# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trace_grpc_microservices_example/DataService/service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='trace_grpc_microservices_example/DataService/service.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n:trace_grpc_microservices_example/DataService/service.proto\"5\n\x16GetCommentsDataRequest\x12\x1b\n\x13\x61pm_trace_parent_id\x18\x01 \x01(\t\"$\n\x14GetCommentsDataReply\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t2R\n\x0b\x44\x61taService\x12\x43\n\x0fGetCommentsData\x12\x17.GetCommentsDataRequest\x1a\x15.GetCommentsDataReply\"\x00\x62\x06proto3')
)




_GETCOMMENTSDATAREQUEST = _descriptor.Descriptor(
  name='GetCommentsDataRequest',
  full_name='GetCommentsDataRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='apm_trace_parent_id', full_name='GetCommentsDataRequest.apm_trace_parent_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=115,
)


_GETCOMMENTSDATAREPLY = _descriptor.Descriptor(
  name='GetCommentsDataReply',
  full_name='GetCommentsDataReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='GetCommentsDataReply.data', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=117,
  serialized_end=153,
)

DESCRIPTOR.message_types_by_name['GetCommentsDataRequest'] = _GETCOMMENTSDATAREQUEST
DESCRIPTOR.message_types_by_name['GetCommentsDataReply'] = _GETCOMMENTSDATAREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetCommentsDataRequest = _reflection.GeneratedProtocolMessageType('GetCommentsDataRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETCOMMENTSDATAREQUEST,
  '__module__' : 'trace_grpc_microservices_example.DataService.service_pb2'
  # @@protoc_insertion_point(class_scope:GetCommentsDataRequest)
  })
_sym_db.RegisterMessage(GetCommentsDataRequest)

GetCommentsDataReply = _reflection.GeneratedProtocolMessageType('GetCommentsDataReply', (_message.Message,), {
  'DESCRIPTOR' : _GETCOMMENTSDATAREPLY,
  '__module__' : 'trace_grpc_microservices_example.DataService.service_pb2'
  # @@protoc_insertion_point(class_scope:GetCommentsDataReply)
  })
_sym_db.RegisterMessage(GetCommentsDataReply)



_DATASERVICE = _descriptor.ServiceDescriptor(
  name='DataService',
  full_name='DataService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=155,
  serialized_end=237,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetCommentsData',
    full_name='DataService.GetCommentsData',
    index=0,
    containing_service=None,
    input_type=_GETCOMMENTSDATAREQUEST,
    output_type=_GETCOMMENTSDATAREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DATASERVICE)

DESCRIPTOR.services_by_name['DataService'] = _DATASERVICE

# @@protoc_insertion_point(module_scope)
