# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: db_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='db_service.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x10\x64\x62_service.proto\x1a\x1bgoogle/protobuf/empty.proto\"$\n\x14GetCommentsDataReply\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t2Q\n\x0b\x44\x61taService\x12\x42\n\x0fGetCommentsData\x12\x16.google.protobuf.Empty\x1a\x15.GetCommentsDataReply\"\x00\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_GETCOMMENTSDATAREPLY = _descriptor.Descriptor(
  name='GetCommentsDataReply',
  full_name='GetCommentsDataReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='GetCommentsDataReply.data', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=85,
)

DESCRIPTOR.message_types_by_name['GetCommentsDataReply'] = _GETCOMMENTSDATAREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetCommentsDataReply = _reflection.GeneratedProtocolMessageType('GetCommentsDataReply', (_message.Message,), {
  'DESCRIPTOR' : _GETCOMMENTSDATAREPLY,
  '__module__' : 'db_service_pb2'
  # @@protoc_insertion_point(class_scope:GetCommentsDataReply)
  })
_sym_db.RegisterMessage(GetCommentsDataReply)



_DATASERVICE = _descriptor.ServiceDescriptor(
  name='DataService',
  full_name='DataService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=87,
  serialized_end=168,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetCommentsData',
    full_name='DataService.GetCommentsData',
    index=0,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_GETCOMMENTSDATAREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DATASERVICE)

DESCRIPTOR.services_by_name['DataService'] = _DATASERVICE

# @@protoc_insertion_point(module_scope)
