version: '3'

services:
  elasticsearch:
    image: elasticsearch:7.9.2
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
    - discovery.type=single-node  
    - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    networks:
      - docker_elk
  logstash:
    image: logstash:7.9.2
    ports:
      - "5000:5000"
    networks:
      - docker_elk
    depends_on:
      - elasticsearch
  kibana:
    image: kibana:7.9.2
    #volumes:
    #  - ./kibana/config/:/etc/kibana/
    ports:
      - "5601:5601"
    networks:
      - docker_elk
    depends_on:
      - elasticsearch

networks:
  docker_elk:
    driver: bridge