apiVersion: v1
kind: Pod
metadata:
  name: fluentd
  namespace: kroos-dev
  labels:
    app: fluentd
spec:
  containers:
  - name: fluentd
    image: ekko771/fluentd-mogo:latest
    ports:
      - containerPort: 24224
    volumeMounts:
      - name: fluentd-config
        mountPath: "/fluentd/etc/fluent.conf"
        subPath: server_fluentd.conf
        readOnly: true
  volumes:
    # You set volumes at the Pod level, then mount them into containers inside that Pod
    - name: fluentd-config
      configMap:
        name: myconfigmap
---
apiVersion: v1
kind: Service
metadata:
  name: fluentd-svc
  namespace: kroos-dev
spec:
  type: ClusterIP
  selector:
    app: fluentd
  ports:
    - protocol: TCP
      port: 24224
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: myconfigmap
  namespace: kroos-dev
data:
  server_fluentd.conf: |-
    <source>
      @type forward
      port 24224
      bind 0.0.0.0
    </source>

    <match app.*>
      @type copy
      <store>
        @type stdout
      </store>
      <store>
        @type file
        path /fluentd/log/app/myapp1
      </store>
      <store>
        @type mongo
        host mongo
        port 27017
        database test_db
        collection test_collection
        <inject>
        # key name of timestamp
        time_key time
        </inject>

        <buffer>
            # flush
            flush_interval 10s
        </buffer>
      </store>
    </match>

    <match mongo_app.*>
      @type copy
      <store>
        @type stdout
      </store>
      <store>
        @type mongo
        host mongodb-svc
        port 27017
        database fluent
        collection fluent_collection
        <inject>
        # key name of timestamp
        time_key time
        </inject>

        <buffer>
            # flush
            flush_interval 10s
        </buffer>
      </store>
    </match>

    <match redis_app.pii>
      @type copy
      <store>
        @type stdout
      </store>
      <store>
      @type redis_store

      host redis-svc
      port 6379
      db 1
      key_path user.name
      key_expire 604800
      <buffer>
            flush_interval 10s
      </buffer>
      </store>
    </match>
