# mongodb.yaml

---
apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  namespace: kroos-dev
  labels:
    app: mongodb
spec:
  containers:
  - name: mongodb
    image: mongo:latest
    ports:
      - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-svc
  namespace: kroos-dev
spec:
  type: ClusterIP
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
