# redis.yaml

---
apiVersion: v1
kind: Pod
metadata:
  name: redis
  namespace: kroos-dev
  labels:
    app: redis
spec:
  containers:
  - name: redis
    image: redis:alpine
    ports:
      - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  namespace: kroos-dev
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
