# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from trace_grpc_microservices_example.AiService import service_pb2 as trace__grpc__microservices__example_dot_AiService_dot_service__pb2


class AiServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.PredictComment = channel.unary_unary(
        '/AiService/PredictComment',
        request_serializer=trace__grpc__microservices__example_dot_AiService_dot_service__pb2.PredictCommentRequest.SerializeToString,
        response_deserializer=trace__grpc__microservices__example_dot_AiService_dot_service__pb2.PredictCommentReply.FromString,
        )


class AiServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def PredictComment(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AiServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'PredictComment': grpc.unary_unary_rpc_method_handler(
          servicer.PredictComment,
          request_deserializer=trace__grpc__microservices__example_dot_AiService_dot_service__pb2.PredictCommentRequest.FromString,
          response_serializer=trace__grpc__microservices__example_dot_AiService_dot_service__pb2.PredictCommentReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'AiService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
