# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ai_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ai_service.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x10\x61i_service.proto\"%\n\x15PredictCommentRequest\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\"#\n\x13PredictCommentReply\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t2M\n\tAiService\x12@\n\x0ePredictComment\x12\x16.PredictCommentRequest\x1a\x14.PredictCommentReply\"\x00\x62\x06proto3')
)




_PREDICTCOMMENTREQUEST = _descriptor.Descriptor(
  name='PredictCommentRequest',
  full_name='PredictCommentRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='PredictCommentRequest.data', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=57,
)


_PREDICTCOMMENTREPLY = _descriptor.Descriptor(
  name='PredictCommentReply',
  full_name='PredictCommentReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='PredictCommentReply.data', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=94,
)

DESCRIPTOR.message_types_by_name['PredictCommentRequest'] = _PREDICTCOMMENTREQUEST
DESCRIPTOR.message_types_by_name['PredictCommentReply'] = _PREDICTCOMMENTREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PredictCommentRequest = _reflection.GeneratedProtocolMessageType('PredictCommentRequest', (_message.Message,), {
  'DESCRIPTOR' : _PREDICTCOMMENTREQUEST,
  '__module__' : 'ai_service_pb2'
  # @@protoc_insertion_point(class_scope:PredictCommentRequest)
  })
_sym_db.RegisterMessage(PredictCommentRequest)

PredictCommentReply = _reflection.GeneratedProtocolMessageType('PredictCommentReply', (_message.Message,), {
  'DESCRIPTOR' : _PREDICTCOMMENTREPLY,
  '__module__' : 'ai_service_pb2'
  # @@protoc_insertion_point(class_scope:PredictCommentReply)
  })
_sym_db.RegisterMessage(PredictCommentReply)



_AISERVICE = _descriptor.ServiceDescriptor(
  name='AiService',
  full_name='AiService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=96,
  serialized_end=173,
  methods=[
  _descriptor.MethodDescriptor(
    name='PredictComment',
    full_name='AiService.PredictComment',
    index=0,
    containing_service=None,
    input_type=_PREDICTCOMMENTREQUEST,
    output_type=_PREDICTCOMMENTREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_AISERVICE)

DESCRIPTOR.services_by_name['AiService'] = _AISERVICE

# @@protoc_insertion_point(module_scope)
